### ISSUE TITLE
Dealing with NA when calculating run_volumes

### ISSUE THREAD

**Issue by Jiazhouchen** [UNCDEPENdLab/dependlab#1]
If NA exists in signal_aligned object; either because a value exists in signal but not in event so there's no timing; or when using value * censor (1/0) method along with regressor that is true for missed trials, line 354 will calculate highesttime variable as NA (by default max function use na.rm=F). Using na.rm=T will resolve this issue.

**Comment by michaelhallquist** [comment]
Thanks for catching that, Jiazhou. Just updated the package with na.rm=TRUE.
