### ISSUE TITLE
fmri.stimulus has object that's not defined

### ISSUE THREAD

**Issue by Jiazhouchen** [UNCDEPENdLab/dependlab#2]
<simpleError in fmri.stimulus(n_vols = n_vols, values = 1, times = times[i],     durations = durations[i], tr = tr, demean = FALSE, center_values = FALSE,     convolve = convolve, a1 = hrf_parameters["a1"], a2 = hrf_parameters["a2"],     b1 = hrf_parameters["b1"], b2 = hrf_parameters["b2"], cc = hrf_parameters["cc"]): object 'ts_multiplier' not found>

**Comment by michaelhallquist** [comment]
I think this resulted from an accidental reversion that Alison committed. I just rolled things back to how they used to be, and it should work, I think
